
title = "Welcome"
author = "Kevin Devine"
#copyright = "2020-2021"
description = "Kevin Devine, PhD"
profilePicture = "images/ProPhoto.jpeg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/42743ba9/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kevindevine16"

[[socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/kmdevine1"

[[socialIcons]]
icon = "ai ai-google-scholar"
title = "e-mail"
url = "https://scholar.google.com/citations?user=j8dOC9AAAAAJ"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:kevindevine16@gmail.com"
